services:
  - type: web
    name: pneumoscan-api
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: MODEL_PATH
        value: model/final_model.keras
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        value: https://pneumo-scan.vercel.app
    healthCheckPath: /health
